services:
  backend:
    image: game_of_tasks
    build:
      context: .
    depends_on:
      postgres:
          condition: service_healthy
    environment:
      PG_PASS: ${PG_PASS}
      PG_USER: ${PG_USER}
      PG_NAME: ${PG_NAME}
    ports:
      - "80:80"
  postgres:
    image: postgres:16.0
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
#      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

#volumes:
#  db-data:
